credentials:
  db:
    admin:
      password: admin
    internal:
      password: admin
    reportdb:
      password: admin
  admin:
    password: admin

global:
  fqdn: "your.fq.dn"

server-helm:
  # All the values for server-helm should follow
  repository: registry.opensuse.org/systemsmanagement/uyuni/master/containerfile/uyuni
  ingress:
    type: traefik
    class: traefik
  # https://github.com/uyuni-project/uyuni/tree/master/containers/server-helm#apparmor
  server:
    superPrivileged: true
  tftp:
    enable: false
